language: android
dist: trusty
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-23
    - extra-google-m2repository

before_script:
  - echo "y" | sdkmanager "platform-tools;26.0.1"

