language: android
install:
   - echo y | android update sdk -u -a -t build-tools-26.0.1

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra
    - android-24
    - build-tools-26.0.1
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
